version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

  errcheck:
    check-type-assertions: true

  govet:
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
